[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "minimal-project"
version = "0.0.0"
description = "A minimal example project"
authors = [ { name = "You" } ]
